### ISSUE TITLE
Error when code has CSS file imported in JS

### ISSUE THREAD

**Issue by rishabhrathod01** [agneym/preact-cli-tailwind#8] opened 2021-02-12 21:51 UTC
### Error message  

✖ ERROR ./style/index.css Module build failed (from ../node_modules/postcss-loader/src/index.js): Error: PostCSS plugin tailwindcss requires PostCSS 8. Migration guide for end-users: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users     at Processor.normalize (./node_modules/postcss/lib/processor.js:153:15) Build failed!

**Comment by agneym** [comment] 2021-02-13 17:22
Duplicate of #7

**Closed as completed by agneym** 2021-02-13 17:22 UTC
